#!/usr/bin/env bash
# Per-user setup inside WSL (no root): $NIKO_HOME tree, uv, shell environment.
#   wsl -d Ubuntu-24.04 -- bash "/mnt/d/Pack/Track Nhad/scripts/wsl/10_user.sh"
set -euo pipefail

NIKO_HOME="${NIKO_HOME:-$HOME/niko}"
mkdir -p "$NIKO_HOME"/{envs,third_party,checkpoints,blender,bench,runs,cache}
mkdir -p "$HOME/.config/niko"

ENV_FILE="$HOME/.config/niko/env.sh"
cat > "$ENV_FILE" <<'EOF'
# Niko Tracker environment (generated by scripts/wsl/10_user.sh)
export NIKO_HOME="$HOME/niko"
export NIKO_REPO="/mnt/d/Pack/Track Nhad"
export CUDA_HOME=/usr/local/cuda-12.8
export PATH="$CUDA_HOME/bin:$HOME/.local/bin:$PATH"
export TORCH_CUDA_ARCH_LIST="12.0"
# uv: cache next to the envs so identical wheels (torch) are hard-linked, not copied
export UV_CACHE_DIR="$NIKO_HOME/cache/uv"
export UV_LINK_MODE=hardlink
export UV_PYTHON_INSTALL_DIR="$NIKO_HOME/cache/python"
export HF_HOME="$NIKO_HOME/cache/hf"
# HF_TOKEN lives only here, outside the repo:  echo 'export HF_TOKEN=hf_...' > ~/.config/niko/secrets.sh
if [ -f "$HOME/.config/niko/secrets.sh" ]; then . "$HOME/.config/niko/secrets.sh"; fi
EOF

# Source it from login shells (bash -lc) and interactive shells.
for rc in "$HOME/.profile" "$HOME/.bashrc"; do
    grep -q "config/niko/env.sh" "$rc" 2>/dev/null || echo 'if [ -f "$HOME/.config/niko/env.sh" ]; then . "$HOME/.config/niko/env.sh"; fi' >> "$rc"
done
. "$ENV_FILE"

if ! command -v uv >/dev/null 2>&1; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
fi
uv --version
echo "NIKO_HOME=$NIKO_HOME  ($(df -h "$NIKO_HOME" | awk 'NR==2 {print $4 " free"}'))"
