; Niko Tracker - Windows installer (Inno Setup 6).
; Niko Tracker Engine - author: Nihad Jihad. Copyright (c) 2026, all rights reserved.
;
; Build:  installer\build.ps1   ->  installer\Output\NikoTracker-Setup-<version>.exe
; The EXE is small: the engine (a prebuilt WSL2 image with the Python environments, installer\engine)
; and the models (from their official sources; SAM 3 with the user's own Hugging Face token) are
; downloaded during setup, with checksums.
;
; Steps:
;   1. hardware check      - hardware_check.ps1: NVIDIA GPU / driver / VRAM, RAM, disk, WSL -> stop on blockers
;   2. WSL2                - when missing: turn it on (administrator window), restart, run setup again
;   3. engine              - download the image parts (SHA-256 checked), join, `wsl --import NikoEngine`
;   4. models              - fetch_checkpoints.py --all --ask-token in a console window (resumable)
;   5. Blender add-on      - install_addon.ps1 (every Blender found, enabled)
; Command line (testing): /NOENGINE=1 skips 3, /NOMODELS=1 skips 4, /ENGINEURL=<base url> another host.

#define AppName "Niko Tracker"
#ifndef AppVersion
  #define AppVersion "0.3.8"
#endif
#define AppPublisher "Nihad Jihad"

[Setup]
AppId={{6A33BBFA-634D-4DE8-9A4E-C853FD59BE42}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
DefaultDirName={autopf}\Niko Tracker
; per user (no administrator prompt): the add-on, WSL distros and the engine all live per user
PrivilegesRequired=lowest
DefaultGroupName=Niko Tracker
OutputBaseFilename=NikoTracker-Setup-{#AppVersion}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
; artwork: installer\art\make_art.py (100 % and 200 % sizes for high-DPI screens)
WizardImageFile=art\wizard_side_1x.bmp,art\wizard_side_2x.bmp
WizardSmallImageFile=art\wizard_small_1x.bmp,art\wizard_small_2x.bmp
SetupIconFile=art\niko.ico
UninstallDisplayIcon={app}\niko.ico
UninstallDisplayName={#AppName} {#AppVersion}
LicenseFile=..\LICENSE
AppCopyright=Copyright (c) 2026 Nihad Jihad. All rights reserved.
InfoAfterFile=after_install.txt
OutputDir=Output

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Components]
Name: "blender"; Description: "Blender add-on (the Niko track tab)"; Types: full custom; Flags: fixed

[Files]
Source: "..\addon\niko_tracker\*.py"; DestDir: "{app}\addon\niko_tracker"; Components: blender
Source: "hardware_check.ps1"; DestDir: "{app}\installer"
Source: "install_addon.ps1"; DestDir: "{app}\installer"
Source: "..\README.md"; DestDir: "{app}"
Source: "..\LICENSE"; DestDir: "{app}"; DestName: "LICENSE.txt"
Source: "..\docs\LICENSES.md"; DestDir: "{app}\docs"
Source: "art\niko.ico"; DestDir: "{app}"

[Icons]
Name: "{group}\Niko Tracker - read me"; Filename: "{app}\README.md"; IconFilename: "{app}\niko.ico"
Name: "{group}\Download the models again"; Filename: "wsl.exe"; Parameters: "-d NikoEngine --exec bash -lc ""cd \""$NIKO_REPO\"" && export UV_PROJECT_ENVIRONMENT=\""$NIKO_HOME/envs/niko\"" && uv run python scripts/fetch_checkpoints.py --all --ask-token; read -p 'Press Enter to close'"""; IconFilename: "{app}\niko.ico"
Name: "{group}\Uninstall Niko Tracker"; Filename: "{uninstallexe}"

[Run]
Filename: "powershell.exe"; Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\installer\install_addon.ps1"" -Source ""{app}\addon\niko_tracker"""; StatusMsg: "Installing the Blender add-on..."; Components: blender; Flags: runhidden waituntilterminated

[Code]
const
  EngineDistro = 'NikoEngine';
  EngineHome = '/home/rudaw/niko';

var
  HwPage: TOutputMsgMemoWizardPage;
  HwOk: Boolean;
  HwJson: AnsiString;
  DownloadPage: TDownloadWizardPage;
  NeedEngine: Boolean;

// generated by build.ps1: EngineVersion, EngineSizeText, EngineTarName, AddEngineParts, JoinEngineParts
#include "engine_parts.iss"

function RunCapture(const Exe, Params: String; var Output: AnsiString): Integer;
var
  Tmp: String;
  Code: Integer;
begin
  Tmp := ExpandConstant('{tmp}\niko_out.txt');
  DeleteFile(Tmp);
  Exec(ExpandConstant('{cmd}'), '/C ""' + Exe + '" ' + Params + ' > "' + Tmp + '" 2>&1"', '', SW_HIDE,
       ewWaitUntilTerminated, Code);
  Output := '';
  LoadStringFromFile(Tmp, Output);
  Result := Code;
end;

// wsl.exe writes UTF-16: drop the zero bytes, then compare whole lines
function WslHasDistro(const Name: String): Boolean;
var
  Raw: AnsiString;
  S, Line: String;
  P: Integer;
begin
  Result := False;
  if RunCapture('wsl.exe', '--list --quiet', Raw) <> 0 then Exit;
  S := String(Raw);
  StringChangeEx(S, #0, '', True);
  StringChangeEx(S, #13, '', True);
  S := S + #10;
  repeat
    P := Pos(#10, S);
    Line := Trim(Copy(S, 1, P - 1));
    Delete(S, 1, P);
    if CompareText(Line, Name) = 0 then
    begin
      Result := True;
      Exit;
    end;
  until S = '';
end;

function WslReady: Boolean;
var
  Raw: AnsiString;
begin
  Result := RunCapture('wsl.exe', '--status', Raw) = 0;
end;

// numeric compare of dotted versions ("0.3.10" > "0.3.8"): <0, 0, >0
function CompareVersions(A, B: String): Integer;
var
  PA, PB, NA, NB: Integer;
begin
  Result := 0;
  while (Result = 0) and ((A <> '') or (B <> '')) do
  begin
    PA := Pos('.', A);
    if PA = 0 then PA := Length(A) + 1;
    PB := Pos('.', B);
    if PB = 0 then PB := Length(B) + 1;
    NA := StrToIntDef(Copy(A, 1, PA - 1), 0);
    NB := StrToIntDef(Copy(B, 1, PB - 1), 0);
    Delete(A, 1, PA);
    Delete(B, 1, PB);
    if NA < NB then Result := -1
    else if NA > NB then Result := 1;
  end;
end;

function InstalledEngineVersion: String;
var
  Raw: AnsiString;
begin
  Result := '';
  if not WslHasDistro(EngineDistro) then Exit;
  // the environments' version (the code inside may be newer: the add-on updates it alone)
  if RunCapture('wsl.exe', '-d ' + EngineDistro + ' --exec cat ' + EngineHome + '/IMAGE_VERSION', Raw) = 0 then
    Result := Trim(String(Raw))
  else if RunCapture('wsl.exe', '-d ' + EngineDistro + ' --exec cat ' + EngineHome + '/engine/ENGINE_VERSION', Raw) = 0 then
    Result := Trim(String(Raw));
end;

function OnDownloadProgress(const Url, FileName: String; const Progress, ProgressMax: Int64): Boolean;
begin
  Result := True;
end;

procedure InitializeWizard;
begin
  HwPage := CreateOutputMsgMemoPage(wpWelcome, 'Checking this computer',
    'GPU, driver, memory, disk and WSL2', 'Niko Tracker needs an NVIDIA GPU with 8 GB or more.', '');
  DownloadPage := CreateDownloadPage('Downloading the tracking engine',
    'About ' + EngineSizeText + ', checked piece by piece. This takes a while.', @OnDownloadProgress);
end;

// once per run; also when the page is never shown (silent install)
procedure RunHardwareCheck;
begin
  if HwJson <> '' then Exit;
  ExtractTemporaryFile('hardware_check.ps1');
  RunCapture('powershell.exe', '-NoProfile -ExecutionPolicy Bypass -File "' +
             ExpandConstant('{tmp}\hardware_check.ps1') + '"', HwJson);
  // Windows PowerShell writes "ok":  true (two spaces), PowerShell 7 one
  HwOk := (Pos('"ok":  true', String(HwJson)) > 0) or (Pos('"ok": true', String(HwJson)) > 0);
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  if CurPageID = HwPage.ID then
  begin
    RunHardwareCheck;
    HwPage.RichEditViewer.Lines.Text := String(HwJson);
  end;
end;

function TurnOnWsl: Boolean;
var
  Code: Integer;
begin
  Result := False;
  if SuppressibleMsgBox('The tracking engine runs in WSL2, which is not turned on yet.' + #13#10#13#10 +
            'Setup can turn it on now (Windows asks for administrator permission). Afterwards restart ' +
            'the computer and run this setup again to install the engine.' + #13#10#13#10 +
            'Turn on WSL2 now?', mbConfirmation, MB_YESNO, IDNO) = IDYES then
    Result := ShellExec('runas', 'wsl.exe', '--install --no-distribution', '', SW_SHOW, ewWaitUntilTerminated, Code);
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  Have: String;
begin
  Result := True;
  if CurPageID = HwPage.ID then RunHardwareCheck;
  if (CurPageID = HwPage.ID) and (not HwOk) then
  begin
    SuppressibleMsgBox('This computer cannot run the tracking engine yet. The "blockers" list above says why.',
           mbError, MB_OK, IDOK);
    Result := False;
  end;
  if CurPageID = wpReady then
  begin
    NeedEngine := False;
    if (EngineVersion = '') or (ExpandConstant('{param:NOENGINE|0}') = '1') then Exit;
    if not WslReady then
    begin
      TurnOnWsl;
      Exit;  // the add-on is still installed; the engine on the next run
    end;
    Have := InstalledEngineVersion;
    if (Have <> '') and (CompareVersions(Have, EngineVersion) >= 0) then Exit;  // same or newer environments
    if Have <> '' then
      if SuppressibleMsgBox('Tracking engine ' + Have + ' is installed. Replacing it with ' + EngineVersion +
                ' also removes the solves stored inside it (copy any you need first).' + #13#10#13#10 +
                'Replace the engine now?', mbConfirmation, MB_YESNO, IDNO) <> IDYES then Exit;
    NeedEngine := True;
    DownloadPage.Clear;
    AddEngineParts(DownloadPage, ExpandConstant('{param:ENGINEURL|' + EngineBaseUrl + '}'));
    DownloadPage.Show;
    try
      try
        DownloadPage.Download;
      except
        if DownloadPage.AbortedByUser then
          Log('engine download aborted by the user')
        else
          SuppressibleMsgBox(AddPeriod(GetExceptionMessage), mbCriticalError, MB_OK, IDOK);
        NeedEngine := False;
        Result := False;
      end;
    finally
      DownloadPage.Hide;
    end;
  end;
end;

procedure InstallEngine;
var
  Code: Integer;
  Tar, Dir, Hw: String;
begin
  WizardForm.StatusLabel.Caption := 'Joining the engine download...';
  Tar := ExpandConstant('{tmp}\') + EngineTarName;
  if not JoinEngineParts(Tar) then
  begin
    SuppressibleMsgBox('The engine download could not be joined.', mbError, MB_OK, IDOK);
    Exit;
  end;
  if WslHasDistro(EngineDistro) then
  begin
    WizardForm.StatusLabel.Caption := 'Removing the previous tracking engine...';
    Exec('wsl.exe', '--unregister ' + EngineDistro, '', SW_HIDE, ewWaitUntilTerminated, Code);
  end;
  WizardForm.StatusLabel.Caption := 'Installing the tracking engine into WSL2 (several minutes)...';
  Dir := ExpandConstant('{localappdata}\NikoTracker\engine');
  ForceDirectories(Dir);
  if not Exec('wsl.exe', '--import ' + EngineDistro + ' "' + Dir + '" "' + Tar + '" --version 2', '', SW_HIDE,
              ewWaitUntilTerminated, Code) or (Code <> 0) then
  begin
    SuppressibleMsgBox('WSL could not import the engine (code ' + IntToStr(Code) + ').', mbError, MB_OK, IDOK);
    Exit;
  end;
  DeleteFile(Tar);
  // the hardware profile decides the engine's memory settings
  RunHardwareCheck;
  Hw := ExpandConstant('{tmp}\hardware.json');
  SaveStringToFile(Hw, HwJson, False);
  Exec(ExpandConstant('{cmd}'), '/C "wsl.exe -d ' + EngineDistro + ' --exec bash -c "cat > ' + EngineHome +
       '/hardware.json" < "' + Hw + '""', '', SW_HIDE, ewWaitUntilTerminated, Code);
end;

procedure DownloadModels;
var
  Code: Integer;
begin
  WizardForm.StatusLabel.Caption := 'Downloading the models (a console window shows the progress)...';
  Exec('wsl.exe', '-d ' + EngineDistro + ' --exec bash -lc "cd \"$NIKO_REPO\" && export UV_PROJECT_ENVIRONMENT=\"$NIKO_HOME/envs/niko\" ' +
       '&& uv run python scripts/fetch_checkpoints.py --all --ask-token; read -p ''Press Enter to close this window''"',
       '', SW_SHOW, ewWaitUntilTerminated, Code);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    if NeedEngine then InstallEngine;
    if WslHasDistro(EngineDistro) and (ExpandConstant('{param:NOMODELS|0}') <> '1') then DownloadModels;
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  Code: Integer;
begin
  if (CurUninstallStep = usUninstall) and WslHasDistro(EngineDistro) then
    if SuppressibleMsgBox('Also remove the tracking engine (WSL distribution ' + EngineDistro + ') and every solve ' +
              'stored inside it?', mbConfirmation, MB_YESNO or MB_DEFBUTTON2, IDNO) = IDYES then
      Exec('wsl.exe', '--unregister ' + EngineDistro, '', SW_HIDE, ewWaitUntilTerminated, Code);
end;
